name: "webhook"
repository: github.com/aquasecurity/trivy-plugin-webhook
version: "0.1.0"
usage: send trivy results to a webhook
description: |-
  A Trivy plugin that sends the trivy results to a webhook endpoint.
  Usage: trivy webhook <trivy args>
platforms:
- selector: # optional
    os: darwin
    arch: amd64
  uri: ./trivy-webhook # where the execution file is (local file, http, git, etc.)
  bin: ./trivy-webhook # path to the execution file
- selector: # optional
    os: linux
    arch: amd64
  uri: https://github.com/aquasecurity/trivy-plugin-webhook/releases/download/v0.1.0/trivy-webhook.tar.gz
  bin: ./trivy-webhook
