name: "webhook"
repository: github.com/aquasecurity/trivy-plugin-webhook
version: "0.2.2"
usage: trivy webhook -- <plugin args> -- <trivy args>
description: |-
  A Trivy plugin that sends the trivy results to a webhook endpoint.
  Usage: trivy webhook -- <plugin args> -- <trivy args>
platforms:
- selector: # optional
    os: darwin
    arch: amd64
  uri: ./trivy-webhook # where the execution file is (local file, http, git, etc.)
  bin: ./trivy-webhook # path to the execution file
- selector: # optional
    os: linux
    arch: amd64
  uri: https://github.com/aquasecurity/trivy-plugin-webhook/releases/download/v0.2.2/trivy-webhook.tar.gz
  bin: ./trivy-webhook
